# src/eventflow/cli.py
from pathlib import Path

import typer
from pydantic import BaseModel

from eventflow import events

app = typer.Typer(help="EventFlow developer CLI.")


@app.callback()
def main() -> None:
    """EventFlow developer CLI."""
    pass


def build_event_registry() -> dict[str, type[BaseModel]]:
    """Map event_type string to its Pydantic model class."""
    registry: dict[str, type[BaseModel]] = {}
    for name in dir(events):
        obj = getattr(events, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, BaseModel)
            and obj is not BaseModel
        ):
            field = obj.model_fields.get("event_type")
            if field is not None and field.default is not None:
                registry[field.default] = obj
    return registry


def to_pascal_case(snake: str) -> str:
    """fraud_detection -> FraudDetection"""
    return "".join(word.capitalize() for word in snake.split("_"))


# Project paths resolved relative to this file
PROJECT_ROOT = Path(__file__).resolve().parents[2]
HANDLERS_DIR = PROJECT_ROOT / "src" / "eventflow" / "handlers"
CONSTRUCTS_DIR = PROJECT_ROOT / "infra" / "lib" / "constructs"
TESTS_DIR = PROJECT_ROOT / "tests" / "test_handlers"


def handler_template(name: str, event_type: str, event_class: str) -> str:
    return f'''# src/eventflow/handlers/{name}_handler.py
# Generated by ef init — implement handler logic below

import json
import os
from typing import Any

import boto3

from eventflow.events import {event_class}

events_client = boto3.client("events")
EVENT_BUS_NAME = os.environ.get("EVENT_BUS_NAME", "eventflow-dev-bus")


def handler(event: dict[str, Any], context: Any) -> None:
    for record in event["Records"]:
        body = json.loads(record["body"])
        detail_type = body["detail-type"]
        detail = body["detail"]

        if detail_type == "{event_type}":
            parsed = {event_class}.model_validate(detail)
            # TODO: implement {name} logic using parsed event
            print(f"Received {{parsed.event_type}} — implement handler")  # noqa: T201
'''


def construct_template(name: str, pascal: str) -> str:
    return f"""// infra/lib/constructs/{name}_construct.ts
// Generated by ef init — wire into EventFlowStack to activate

import * as events from "aws-cdk-lib/aws-events";
import {{ Construct }} from "constructs";

export class {pascal}Construct extends Construct {{
  constructor(scope: Construct, id: string, bus: events.EventBus) {{
    super(scope, id);

    // TODO: wire queue, Lambda, and EventBridge rule
  }}
}}
"""


def test_template(name: str) -> str:
    return f"""# tests/test_handlers/test_{name}_handler.py
# Generated by ef init — implement tests below


def test_{name}_handler_placeholder() -> None:
    # TODO: implement handler tests
    pass
"""


@app.command()
def init(
    name: str = typer.Option(
        None, "--name", help="Consumer name in snake_case (e.g. fraud_detection)"
    ),
    event_type: str = typer.Option(
        None, "--event-type", help="Event type to consume (e.g. order.placed)"
    ),
) -> None:
    """Scaffold a new event consumer."""
    registry = build_event_registry()

    # Interactive prompts if flags not provided
    if name is None:
        name = typer.prompt("Consumer name")
    if event_type is None:
        event_type = typer.prompt("Event type")

    # Validate event type
    if event_type not in registry:
        typer.echo(f"\nError: Unknown event type '{event_type}'.")
        typer.echo("  Run 'ef list-events' to see all registered event types.")
        raise typer.Exit(code=1)

    handler_path = HANDLERS_DIR / f"{name}_handler.py"
    construct_path = CONSTRUCTS_DIR / f"{name}_construct.ts"
    test_path = TESTS_DIR / f"test_{name}_handler.py"

    # Duplicate detection
    if handler_path.exists():
        typer.echo(f"\nError: Consumer '{name}' already exists.")
        typer.echo(f"  {handler_path.relative_to(PROJECT_ROOT)} already exists.")
        typer.echo(
            "\nUse a different name or delete the existing files before reinitialising."
        )
        raise typer.Exit(code=1)

    pascal = to_pascal_case(name)
    event_class = registry[event_type].__name__

    typer.echo(f"\nScaffolding {name} consumer...\n")

    # Ensure directories exist
    HANDLERS_DIR.mkdir(parents=True, exist_ok=True)
    CONSTRUCTS_DIR.mkdir(parents=True, exist_ok=True)
    TESTS_DIR.mkdir(parents=True, exist_ok=True)

    handler_path.write_text(handler_template(name, event_type, event_class))
    construct_path.write_text(construct_template(name, pascal))
    test_path.write_text(test_template(name))

    typer.echo(f"  Created {handler_path.relative_to(PROJECT_ROOT)}")
    typer.echo(f"  Created {construct_path.relative_to(PROJECT_ROOT)}")
    typer.echo(f"  Created {test_path.relative_to(PROJECT_ROOT)}")

    typer.echo(f"\n\u2713 {name} consumer scaffolded successfully.\n")
    typer.echo("Next steps:")
    typer.echo(
        f"  1. Implement the handler in {handler_path.relative_to(PROJECT_ROOT)}"
    )
    typer.echo("  2. Add the construct to infra/lib/eventflow-stack.ts")
    typer.echo(f"  3. Run: uv run pytest {test_path.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    app()
