import json
import os
from pathlib import Path
from typing import Any

import typer
from pydantic import BaseModel, ValidationError

from eventflow import events

app = typer.Typer(help="EventFlow developer CLI.")


@app.callback()
def main() -> None:
    """EventFlow developer CLI."""
    pass


def build_event_registry() -> dict[str, type[BaseModel]]:
    """Map event_type string to its Pydantic model class."""
    registry: dict[str, type[BaseModel]] = {}
    for name in dir(events):
        obj = getattr(events, name)
        if (
            isinstance(obj, type)
            and issubclass(obj, BaseModel)
            and obj is not BaseModel
        ):
            field = obj.model_fields.get("event_type")
            if field is not None and field.default is not None:
                registry[field.default] = obj
    return registry


def to_pascal_case(snake: str) -> str:
    """fraud_detection -> FraudDetection"""
    return "".join(word.capitalize() for word in snake.split("_"))


# Project paths resolved relative to this file
PROJECT_ROOT = Path(__file__).resolve().parents[2]
HANDLERS_DIR = PROJECT_ROOT / "src" / "eventflow" / "handlers"
CONSTRUCTS_DIR = PROJECT_ROOT / "infra" / "lib" / "constructs"
TESTS_DIR = PROJECT_ROOT / "tests" / "test_handlers"


def handler_template(name: str, event_type: str, event_class: str) -> str:
    return f'''# src/eventflow/handlers/{name}_handler.py
# Generated by ef init — implement handler logic below

import json
import os
from typing import Any

import boto3

from eventflow.events import {event_class}

events_client = boto3.client("events")
EVENT_BUS_NAME = os.environ.get("EVENT_BUS_NAME", "eventflow-dev-bus")


def handler(event: dict[str, Any], context: Any) -> None:
    for record in event["Records"]:
        body = json.loads(record["body"])
        detail_type = body["detail-type"]
        detail = body["detail"]

        if detail_type == "{event_type}":
            parsed = {event_class}.model_validate(detail)
            # TODO: implement {name} logic using parsed event
            print(f"Received {{parsed.event_type}} — implement handler")  # noqa: T201
'''


def construct_template(name: str, pascal: str) -> str:
    return f"""// infra/lib/constructs/{name}_construct.ts
// Generated by ef init — wire into EventFlowStack to activate

import * as events from "aws-cdk-lib/aws-events";
import {{ Construct }} from "constructs";

export class {pascal}Construct extends Construct {{
  constructor(scope: Construct, id: string, bus: events.EventBus) {{
    super(scope, id);

    // TODO: wire queue, Lambda, and EventBridge rule
  }}
}}
"""


def test_template(name: str) -> str:
    return f"""# tests/test_handlers/test_{name}_handler.py
# Generated by ef init — implement tests below


def test_{name}_handler_placeholder() -> None:
    # TODO: implement handler tests
    pass
"""


@app.command()
def init(
    name: str = typer.Option(
        None, "--name", help="Consumer name in snake_case (e.g. fraud_detection)"
    ),
    event_type: str = typer.Option(
        None, "--event-type", help="Event type to consume (e.g. order.placed)"
    ),
) -> None:
    """Scaffold a new event consumer."""
    registry = build_event_registry()

    # Interactive prompts if flags not provided
    if name is None:
        name = typer.prompt("Consumer name")
    if event_type is None:
        event_type = typer.prompt("Event type")

    # Validate event type
    if event_type not in registry:
        typer.echo(f"\nError: Unknown event type '{event_type}'.")
        typer.echo("  Run 'ef list-events' to see all registered event types.")
        raise typer.Exit(code=1)

    handler_path = HANDLERS_DIR / f"{name}_handler.py"
    construct_path = CONSTRUCTS_DIR / f"{name}_construct.ts"
    test_path = TESTS_DIR / f"test_{name}_handler.py"

    # Duplicate detection
    if handler_path.exists():
        typer.echo(f"\nError: Consumer '{name}' already exists.")
        typer.echo(f"  {handler_path.relative_to(PROJECT_ROOT)} already exists.")
        typer.echo(
            "\nUse a different name or delete the existing files before reinitialising."
        )
        raise typer.Exit(code=1)

    pascal = to_pascal_case(name)
    event_class = registry[event_type].__name__

    typer.echo(f"\nScaffolding {name} consumer...\n")

    # Ensure directories exist
    HANDLERS_DIR.mkdir(parents=True, exist_ok=True)
    CONSTRUCTS_DIR.mkdir(parents=True, exist_ok=True)
    TESTS_DIR.mkdir(parents=True, exist_ok=True)

    handler_path.write_text(handler_template(name, event_type, event_class))
    construct_path.write_text(construct_template(name, pascal))
    test_path.write_text(test_template(name))

    typer.echo(f"  Created {handler_path.relative_to(PROJECT_ROOT)}")
    typer.echo(f"  Created {construct_path.relative_to(PROJECT_ROOT)}")
    typer.echo(f"  Created {test_path.relative_to(PROJECT_ROOT)}")

    typer.echo(f"\n\u2713 {name} consumer scaffolded successfully.\n")
    typer.echo("Next steps:")
    typer.echo(
        f"  1. Implement the handler in {handler_path.relative_to(PROJECT_ROOT)}"
    )
    typer.echo("  2. Add the construct to infra/lib/eventflow-stack.ts")
    typer.echo(f"  3. Run: uv run pytest {test_path.relative_to(PROJECT_ROOT)}")


# Maps an event_type prefix to the service that produces it, for chain display.
EVENT_PRODUCERS = {
    "order": "OrderService",
    "stock": "InventoryService",
    "payment": "PaymentService",
    "customer": "NotificationService",
}


def _producer_for(event_type: str) -> str:
    """order.placed -> OrderService"""
    prefix = event_type.split(".", 1)[0]
    return EVENT_PRODUCERS.get(prefix, "Unknown")


def _emit_local(event_obj: BaseModel) -> None:
    """Run the event through the in-memory bus and print the resulting chain."""
    from eventflow.bus import EventBus
    from eventflow.services.inventory_service import InventoryService
    from eventflow.services.notification_service import NotificationService
    from eventflow.services.order_service import OrderService
    from eventflow.services.payment_service import PaymentService

    bus = EventBus()

    # Collect every published event in emission order. Subscribe the collector
    # before the services so it observes the initial event too.
    chain: list[Any] = []
    for event_type in build_event_registry():
        bus.subscribe(event_type, chain.append)

    # Register all four services so the full pipeline reacts to the event.
    OrderService(bus)
    InventoryService(bus)
    PaymentService(bus)
    NotificationService(bus)

    typer.echo("\nRunning in local mode...\n")

    # Services log to stdout as they handle events; suppress that noise so the
    # printed chain is the clean, ordered summary the developer wants to see.
    import contextlib
    import io

    with contextlib.redirect_stdout(io.StringIO()):
        bus.publish(event_obj)

    if not chain:
        typer.echo(
            f"No downstream handlers fired for '{event_obj.event_type}'."  # type: ignore[attr-defined]
        )
        typer.echo("The event was emitted but no service consumes it.")
        return

    typer.echo("Event chain:")
    for emitted in chain:
        producer = _producer_for(emitted.event_type)
        typer.echo(f"  → {emitted.event_type:<22}({producer})")

    typer.echo(f"\n✓ {len(chain)} events emitted. Pipeline completed successfully.")


def _emit_aws(event_obj: BaseModel, event_type: str, bus_name: str | None) -> None:
    """Publish the event to the deployed EventBridge bus via boto3."""
    import boto3
    from botocore.exceptions import BotoCoreError, ClientError

    resolved_bus = bus_name or os.environ.get("EVENT_BUS_NAME") or "eventflow-dev-bus"
    region = (
        os.environ.get("AWS_REGION")
        or os.environ.get("AWS_DEFAULT_REGION")
        or boto3.session.Session().region_name
        or "us-east-1"
    )

    typer.echo(f"\nPublishing to EventBridge bus: {resolved_bus} ({region})...\n")

    detail = event_obj.model_dump(mode="json")

    try:
        client = boto3.client("events", region_name=region)
        response = client.put_events(
            Entries=[
                {
                    "Source": "eventflow.cli",
                    "DetailType": event_type,
                    "Detail": json.dumps(detail),
                    "EventBusName": resolved_bus,
                }
            ]
        )
    except (BotoCoreError, ClientError) as e:
        typer.echo("\nError: Failed to publish to EventBridge.")
        typer.echo(f"  {e}")
        raise typer.Exit(code=1)

    if response.get("FailedEntryCount", 0):
        entry = response["Entries"][0]
        typer.echo("\nError: EventBridge rejected the event.")
        typer.echo(f"  {entry.get('ErrorCode')}: {entry.get('ErrorMessage')}")
        raise typer.Exit(code=1)

    event_id = getattr(event_obj, "event_id", None)
    typer.echo("✓ Event published successfully.")
    typer.echo(f"  event_type:  {event_type}")
    typer.echo(f"  event_id:    {event_id}")
    typer.echo(f"  bus:         {resolved_bus}")
    typer.echo("\nRun 'uv run python scripts/smoke_test.py' to verify end-to-end.")


@app.command()
def emit(
    event_type: str = typer.Option(..., "--event-type", help="Event type to emit"),
    payload: str = typer.Option(..., "--payload", help="Event payload as JSON"),
    env: str = typer.Option("local", "--env", help="Target: local or aws"),
    bus_name: str = typer.Option(
        None,
        "--bus-name",
        help="EventBridge bus name (default: $EVENT_BUS_NAME or eventflow-dev-bus)",
    ),
) -> None:
    """Publish a test event to the local or AWS bus."""
    registry = build_event_registry()

    # Validate event type
    if event_type not in registry:
        typer.echo(f"\nError: Unknown event type '{event_type}'.")
        typer.echo("  Run 'ef list-events' to see all registered event types.")
        raise typer.Exit(code=1)

    # Parse JSON payload
    try:
        payload_dict = json.loads(payload)
    except json.JSONDecodeError as e:
        typer.echo("\nError: Invalid JSON payload.")
        typer.echo(f"  {e}")
        raise typer.Exit(code=1)

    # Validate against the event model
    event_class = registry[event_type]
    try:
        event_obj = event_class.model_validate(payload_dict)
    except ValidationError as e:
        typer.echo(f"\nError: Payload validation failed for '{event_type}'.")
        for err in e.errors():
            loc = ".".join(str(part) for part in err["loc"]) or "(root)"
            typer.echo(f"  {loc}: {err['msg']}")
        typer.echo(f"\nRun 'ef list-events {event_type}' to see required fields.")
        raise typer.Exit(code=1)

    if env == "local":
        _emit_local(event_obj)
    elif env == "aws":
        _emit_aws(event_obj, event_type, bus_name)
    else:
        typer.echo(f"\nError: Unknown env '{env}'. Use 'local' or 'aws'.")
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
